# Generated by Django 3.2.4 on 2021-07-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=13)),
                ('national_id', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('nairobi', 'Nairobi'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru'), ('eldoret', 'Eldoret'), ('Mombasa', 'Mombasa'), ('kisii', 'Kisii')], max_length=20)),
                ('destination', models.CharField(choices=[('nairobi', 'Nairobi'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru'), ('eldoret', 'Eldoret'), ('Mombasa', 'Mombasa'), ('kisii', 'Kisii')], max_length=20)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookerserver.myuser')),
                ('staff_id', models.CharField(default=None, max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('bookerserver.myuser',),
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookerserver.myuser')),
            ],
            options={
                'abstract': False,
            },
            bases=('bookerserver.myuser',),
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('capacity', models.DecimalField(decimal_places=0, max_digits=2)),
                ('booked', models.DecimalField(decimal_places=0, max_digits=2)),
                ('is_full', models.BooleanField(default=False)),
                ('routes', models.TextField()),
                ('rates', models.FloatField(default=1.0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookerserver.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('payment_id', models.CharField(max_length=50)),
                ('departure_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('I', 'Waiting Confirmation'), ('B', 'Booked'), ('C', 'Cancelled')], default='I', max_length=2)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookerserver.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookerserver.routes')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookerserver.passenger')),
            ],
        ),
    ]
